import '../models/studio_models.dart';

class PropertySection {
  const PropertySection(this.name, this.values);
  final String name;
  final Map<String, dynamic> values;
}

class PropertyInspector {
  const PropertyInspector();
  List<PropertySection> inspect(EngineeringTreeNode node) => [
    PropertySection('Identity', {
      'id': node.id,
      'name': node.name,
      'type': node.type.name,
      'status': node.status,
    }),
    PropertySection('Engineering', {
      'confidence': node.confidence,
      'visible': node.visible,
      'locked': node.locked,
      'origin': node.context['origin'],
      'normal': node.context['normal'],
      'area': node.context['area'],
      'dna': node.context['dna'],
      'dependencies': node.context['dependencies'],
      'persistentId': node.context['persistentId'],
      'valid': node.context['valid'],
      'diagnostics': node.context['diagnostics'],
      'featureId': node.context['featureId'],
      'parameters': node.context['parameters'],
      'shapeHandle': node.context['shapeHandle'],
      'persistentIds': node.context['persistentIds'],
      'history': node.context['history'],
      'buildTimeMicros': node.context['buildTimeMicros'],
      'strategy': node.context['strategy'],
      'predictedContinuity': node.context['predictedContinuity'],
      'justification': node.context['justification'],
      'regions': node.context['regions'],
      'alternatives': node.context['alternatives'],
      'surfaceScore': node.context['surfaceScore'],
      'surfaceType': node.context['surfaceType'],
      'evidence': node.context['evidence'],
      'revision': node.context['revision'],
      'hybridStrategy': node.context['hybridStrategy'],
      'neighbors': node.context['neighbors'],
      'selectedAlternative': node.context['selectedAlternative'],
      'discardedAlternatives': node.context['discardedAlternatives'],
      'topoDSType': node.context['topoDSType'],
      'kernelId': node.context['kernelId'],
      'kernelVersion': node.context['kernelVersion'],
      'kernelCapabilities': node.context['kernelCapabilities'],
      'nativeDiagnostics': node.context['nativeDiagnostics'],
    }),
    if (node.type.name == 'sketch')
      PropertySection('Sketch', {
        'persistentId': node.context['persistentId'],
        'entityType': node.context['entityType'],
        'plane': node.context['plane'],
        'coordinates': node.context['coordinates'],
        'construction': node.context['construction'],
        'reference': node.context['reference'],
        'visibility': node.visible,
        'lock': node.locked,
        'diagnostics': node.context['diagnostics'],
      }),
    if (node.context['constraintType'] != null)
      PropertySection('Constraint', {
        'constraintType': node.context['constraintType'],
        'status': node.context['status'],
        'driving': node.context['driving'],
        'driven': node.context['driven'],
        'priority': node.context['priority'],
        'solved': node.context['solved'],
        'references': node.context['references'],
        'diagnostics': node.context['diagnostics'],
        'timestamp': node.context['timestamp'],
        'persistentId': node.context['persistentId'],
      }),
    if (node.context['editorEntity'] == true)
      PropertySection('Sketch Editor', {
        'coordinates': node.context['coordinates'],
        'length': node.context['length'],
        'radius': node.context['radius'],
        'diameter': node.context['diameter'],
        'angle': node.context['angle'],
        'construction': node.context['construction'],
        'reference': node.context['reference'],
        'driving': node.context['driving'],
        'driven': node.context['driven'],
        'constraintCount': node.context['constraintCount'],
        'degreesOfFreedom': node.context['degreesOfFreedom'],
        'selectionState': node.context['selectionState'],
        'persistentId': node.context['persistentId'],
        'history': node.context['history'],
        'diagnostics': node.context['diagnostics'],
      }),
    if (node.context['profileRecognition'] == true)
      PropertySection('Profile Recognition', {
        'profileType': node.context['profileType'],
        'loopCount': node.context['loopCount'],
        'regionCount': node.context['regionCount'],
        'area': node.context['area'],
        'perimeter': node.context['perimeter'],
        'orientation': node.context['orientation'],
        'topologyStatus': node.context['topologyStatus'],
        'readiness': node.context['readiness'],
        'quality': node.context['quality'],
        'intent': node.context['intent'],
        'confidence': node.context['confidence'],
        'persistentId': node.context['persistentId'],
      }),
    if (node.context['featurePlatform'] == true)
      PropertySection('Feature Platform', {
        'featureType': node.context['featureType'],
        'parameters': node.context['parameters'],
        'references': node.context['references'],
        'dependencies': node.context['dependencies'],
        'timelinePosition': node.context['timelinePosition'],
        'executionState': node.context['executionState'],
        'suppression': node.context['suppression'],
        'persistentId': node.context['persistentId'],
        'diagnostics': node.context['diagnostics'],
      }),
    if (node.context['extrudeFeature'] == true)
      PropertySection('Extrude Feature', {
        'extrudeType': node.context['extrudeType'],
        'distance': node.context['distance'],
        'direction': node.context['direction'],
        'profile': node.context['profile'],
        'target': node.context['target'],
        'merge': node.context['merge'],
        'draft': node.context['draft'],
        'persistentId': node.context['persistentId'],
        'history': node.context['history'],
        'dependencies': node.context['dependencies'],
        'kernelStatus': node.context['kernelStatus'],
        'quality': node.context['quality'],
      }),
    if (node.context['revolveFeature'] == true)
      PropertySection('Revolve Feature', {
        'revolveType': node.context['revolveType'],
        'axis': node.context['axis'],
        'angle': node.context['angle'],
        'direction': node.context['direction'],
        'merge': node.context['merge'],
        'body': node.context['body'],
        'references': node.context['references'],
        'persistentId': node.context['persistentId'],
        'history': node.context['history'],
        'dependencies': node.context['dependencies'],
        'quality': node.context['quality'],
        'kernelStatus': node.context['kernelStatus'],
      }),
    if (node.context['transitionFeature'] == true)
      PropertySection('Transition Feature', {
        'transitionType': node.context['transitionType'],
        'profiles': node.context['profiles'],
        'sections': node.context['sections'],
        'paths': node.context['paths'],
        'guides': node.context['guides'],
        'references': node.context['references'],
        'shapeHandle': node.context['shapeHandle'],
        'kernelStatus': node.context['kernelStatus'],
        'dependencies': node.context['dependencies'],
        'history': node.context['history'],
        'quality': node.context['quality'],
      }),
    if (node.context['referenceGeometry'] == true)
      PropertySection('Reference Geometry', {
        'type': node.context['referenceType'],
        'constructionMethod': node.context['constructionMethod'],
        'dependencies': node.context['dependencies'],
        'persistentId': node.context['persistentId'],
        'history': node.context['history'],
        'quality': node.context['quality'],
        'visibility': node.context['visibility'],
        'state': node.context['state'],
      }),
    if (node.context['alignmentFeature'] == true)
      PropertySection('Alignment', {
        'type': node.context['alignmentType'],
        'references': node.context['references'],
        'transformation': node.context['transformation'],
        'matrix': node.context['matrix'],
        'rotation': node.context['rotation'],
        'translation': node.context['translation'],
        'quality': node.context['quality'],
        'accuracy': node.context['accuracy'],
        'history': node.context['history'],
        'persistentId': node.context['persistentId'],
      }),
    if (node.context['liveValidation'] == true)
      PropertySection('Live Validation', {
        'maximumError': node.context['maximumError'],
        'averageError': node.context['averageError'],
        'rms': node.context['rms'],
        'tolerance': node.context['tolerance'],
        'quality': node.context['quality'],
        'confidence': node.context['confidence'],
        'lastUpdate': node.context['lastUpdate'],
        'affectedRegions': node.context['affectedRegions'],
        'responsibleFeature': node.context['responsibleFeature'],
      }),
    if (node.context['engineeringIntelligence'] == true)
      PropertySection('Engineering Intelligence', {
        'engineeringScore': node.context['engineeringScore'],
        'projectHealth': node.context['projectHealth'],
        'lastRecommendation': node.context['lastRecommendation'],
        'confidence': node.context['confidence'],
        'reason': node.context['reason'],
        'expectedImprovement': node.context['expectedImprovement'],
        'impact': node.context['impact'],
      }),
    PropertySection(
      'Analytics',
      (node.context['analytics'] as Map?)?.cast<String, dynamic>() ?? const {},
    ),
  ];
}
